### ISSUE TITLE
Can not load library compiled with mkl

### ISSUE THREAD

**Issue by SuperBo** [intel/pyMIC#15]
pyMIC can load library compiled without mkl normally. But when it come to library that compile link to mkl, there are some errors. This error happen when I run examples/dgemm/dgemm.py

Detailes :

```
PYMIC: debug level set to 1000
PYMIC: tracing is disabled
PYMIC: found 2 device(s)
PYMIC: created stream 0x1219360 for device 0
PYMIC: created stream 0x1229400 for device 1
PYMIC: searching for liboffload_array.so in 
PYMIC:     looking for liboffload_array.so in /usr/lib/python2.7/site-packages/pymic
PYMIC: loading '/usr/lib/python2.7/site-packages/pymic/liboffload_array.so' on device 0
PYMIC: successfully loaded '/usr/lib/python2.7/site-packages/pymic/liboffload_array.so' on device 0 with handle 0x7fa7f4001220
PYMIC: searching for liboffload_array.so in 
PYMIC:     looking for liboffload_array.so in /usr/lib/python2.7/site-packages/pymic
PYMIC: loading '/usr/lib/python2.7/site-packages/pymic/liboffload_array.so' on device 1
PYMIC: successfully loaded 'usr/lib/python2.7/site-packages/pymic/liboffload_array.so' on device 1 with handle 0x7f0b50001220
PYMIC: starting initialization of the offload infrastructure
PYMIC: loading supporting pyMIC libraries on all devices
PYMIC: searching for libdgemm.so in 
PYMIC:     looking for libdgemm.so in /usr/lib/python2.7/site-packages/pymic
PYMIC:     looking for libdgemm.so in 
PYMIC: loading 'libdgemm.so' on device 0
caught!
Traceback (most recent call last):
  File "dgemm.py", line 41, in <module>
    library = device.load_library("libdgemm.so")
  File "/usr/lib/python2.7/site-packages/pymic/_tracing.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pymic/offload_device.py", line 168, in load_library
    return OffloadLibrary(libraries[0], device=self)
  File "/usr/lib/python2.7/site-packages/pymic/offload_library.py", line 125, in __init__
    filename)
  File "pymic_libxstream.pyx", line 238, in pymic.pymic_libxstream.pymic_library_load (src/pymic_libxstream.cpp:3943)
  File "pymic_libxstream.pyx", line 231, in pymic.pymic_libxstream._c_pymic_library_load (src/pymic_libxstream.cpp:3757)
pymic.offload_error.OffloadError: Could not load library 'libdgemm.so' on device 0
offload error: cannot unload library from the device 0 (error code 14)
```

Testbed:
```
Intel Xeon Phi 7120P
Redhat 7.2
Intel® MPSS 3.7.2
```

**Comment by mjklemm** [comment]
Hi,

the dgemm.py example needs to have the MKL libraries on the device.  There are two ways to do this.

1. copy all MKL libs from the /opt/intel/compilers_and_libraries folder (the exact path depends on your installation) to /lib64 on the coprocessor device.
2. use an NFS export from the host to the coprocessor to make /opt/intel available on the coprocessor by mounting the NFS export there.  Then you can use the PYMIC_LD_LIBRARY_PATH environment variable to tell pyMIC to find library dependencies in the NFS import.

HTH

Cheers,
        -michael

**Comment by SuperBo** [comment]
I have already mount Intel Parallel Studio on Xeon Phi card via nfs but this error still occurs.

It turn out that I didn't source env.sh before running dgemm example. After sourcing env.sh, dgemm run normally.

Thank you for your support!
P/s: there still unload error.
`offload error: cannot unload library from the device 0 (error code 14)
`

**Comment by mjklemm** [comment]
Very good! Great that you've been able to resolve this issue.  The env.sh script shows which environment variables to set in case you need other dependencies for your own libraries.

The offload error at the end seems to come from the Intel Compiler libraries.  Which is the version of the compiler you're using?

**Comment by SuperBo** [comment]
I'm using Intel compiler from Intel® Parallel Studio XE 2017 update 1
```
$ icc --version
icc (ICC) 17.0.1 20161005
```

**Comment by mjklemm** [comment]
The problem is that dependences of shared-object libraries are not copied automatically.  For MKL, one can manually copy the MKL shared-object libraries through the scp command (for mic0, similar for other coprocessors in the system):

```scp $MKLROOT/lib/mic/*.so mic0:/lib64```

If home-brew libraries have dependencies, then they can be copied with similar scp commands targeting /lib64 on the MIC devices.
