### ISSUE TITLE
Cypthon Offload Support

### ISSUE THREAD

**Issue by mjklemm** [intel/pyMIC#18]
pyMIC requires programmers to write native kernels in C/C++ (or Fortran) to run on a coprocessor device. Support for Cython code would make programmers' lifes a bit easier, as it would allow them to write more Pythonesque code and then compile it to native coprocessor code.

**Comment by SuperBo** [comment]
I think we can build an Cython module like cython.parallel module to support Cython users

**Comment by mjklemm** [comment]
The main reason why Cython support for the target side is not there yet, is that I had to hack too many things to make Cython cross-compile for the Xeon Phi coprocessor.  I considered that to not be very productive and stable.  The other thing that needs to be solved is to properly unmarshal the data so that Cython code can pick it up.  And of course some smaller pyMIC offload library that contains all the magic to invoke the Cython code.
